.circleci/config.yml
.eslintrc.cjs
.gitignore
tsconfig.json
vite.config.ts

SS-8 Add CI pipeline

---

src/api/services/stationService.ts
src/http/tanstack/react-query.ts
src/main.tsx
src/pages/station/station-list.container.tsx
src/pages/station/station.edit.tsx
types/api.ts

feat: Update and create station

---

src/api/apiClient.ts
src/api/services/managerService.ts
src/pages/manager/manager-list.container.tsx
src/pages/manager/manger.edit.tsx
types/entity.ts

feat: CRUD manager

---

src/api/apiClient.ts
src/api/data/data.json
src/api/services/userService.ts
src/components/upload-button/index.tsx
src/http/tanstack/react-query.ts
src/pages/station/station-list.container.tsx
src/pages/station/station.edit.tsx
src/pages/station/type.ts
src/store/userStore.ts

feat: Add select city

---

src/layouts/dashboard/header.tsx
src/layouts/dashboard/layout.tsx

hotfix: use env insted of hardcode

---

src/api/apiClient.ts
src/api/services/notiService.ts
src/api/services/stationService.ts
src/layouts/_common/notice.tsx
src/pages/pricing/pricing-list.container.tsx

feat: noti feat

---

src/api/services/stationService.ts
src/pages/pricing/pricing-list.default.tsx
src/pages/pricing/pricingDefault.create.tsx
types/entity.ts

fix: update default pricing

---

src/pages/admin/station/station.edit.tsx

fix: Update choose location

---

package.json

fix: update pacakge json

---

src/pages/station/checkout.create.tsx

fix: reload after payment

---

src/layouts/_common/notice.tsx

hotfix: fix nullable token

---

.env
.env.development
.env.production
src/api/services/admin/dashboardService.ts
src/api/services/stationService.ts
src/components/chart/AdminLineChart.tsx
src/components/chart/EChart.tsx
src/components/chart/LineChart.tsx
src/components/chart/configs/adminLineChart.ts
src/components/chart/configs/eChart.ts
src/http/tanstack/react-query.ts
src/layouts/_common/account-dropdown.tsx
src/pages/admin/dashboard/index.tsx
src/pages/dashboard/index.tsx
src/store/userStore.ts

hotfix: update dashboard feature

---

src/api/services/stationService.ts

hotfix: update update by cash

---

src/pages/station/checkout.create.tsx

hotfix: fix checkout typo

---

.env
.env.development
.env.production
src/api/services/stationService.ts
src/layouts/_common/notice.tsx
src/pages/staff/packages.info.tsx
src/pages/staff/shelf-list.container.tsx
src/pages/staff/zone-list.container.tsx
src/pages/station/checkout.create.tsx

hotfix: fix checkout feat

---

src/layouts/_common/notice.tsx

hotfix: fix notice use server

---

src/api/services/stationService.ts
src/pages/staff/staff-list.station.tsx
src/pages/station/expire.create.tsx

Hotfix disable create zone staff

---

src/api/services/stationService.ts
src/components/chart/AdminLineChart.tsx
src/components/chart/LineChart.tsx
src/layouts/_common/notice.tsx
src/pages/package/package-list.manager.tsx
src/pages/staff/expire.create.tsx
src/pages/staff/packages.detail.tsx
src/pages/staff/packages.info.tsx
src/pages/staff/shelf-list.container.tsx
src/pages/staff/staff-list.container.tsx
src/pages/staff/zone-list.container.tsx

hotfix: fix staff

---

src/pages/staff/checkin.create.tsx
src/pages/staff/packages.detail.tsx
src/pages/station/checkin.create.tsx
src/pages/station/checkout.create.tsx
src/pages/station/packages.detail.tsx

hotfix: kg to g

---

src/pages/station/checkout.create.tsx

hotfix: checkout confirm

---

src/api/services/stationService.ts
src/pages/staff/checkin.create.tsx
src/pages/staff/expire.create.tsx
src/pages/staff/packages.detail.tsx
src/pages/staff/packages.info.tsx
src/pages/staff/shelf-list.container.tsx
src/pages/staff/zone-list.container.tsx
src/pages/station/checkin.create.tsx
src/pages/station/expire.create.tsx
src/pages/station/packages.detail.tsx
src/pages/station/packages.info.tsx
src/pages/station/zone-list.container.tsx

hotfix: fix staff bug

---

src/api/services/stationService.ts
src/components/debounce-search/index.tsx
src/pages/package/package-list.manager.tsx
src/pages/payment/payment.detail.tsx
src/pages/pricing/pricing-list.default.tsx
src/pages/staff/checkin.create.tsx
src/pages/station/checkin.create.tsx

feat: add debouce search user

---

src/layouts/_common/notice.tsx
src/pages/admin/manager/station-list.manager.tsx
src/pages/admin/station/station-list.container.tsx
src/pages/station/station-list.container.tsx

feat: fix bug payment

---

src/api/services/admin/managerService.ts
src/api/services/admin/stationService.ts
src/api/services/stationService.ts
src/pages/admin/manager/manager-list.container.tsx
src/pages/admin/manager/station-list.manager.tsx
src/pages/admin/station/pricing-list.container-admin.tsx
src/pages/admin/station/pricing-list.default-admin.tsx
src/pages/admin/station/staff-list.user-admin.tsx
src/pages/admin/station/staff.create-admin.tsx
src/pages/pricing/pricing-list.container.tsx
src/pages/pricing/pricing-list.default.tsx

hotfix: fix bug 31-05

---

src/pages/admin/station/pricing-list.default-admin.tsx
src/pages/admin/station/pricingDefault.modal-admin.tsx
src/pages/pricing/pricingDefault.modal.tsx
src/pages/station/checkout.create.tsx

hotfix: correct text
